# Generated by Django 5.1.6 on 2025-02-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(unique=True)),
                ('num_blocks', models.IntegerField()),
                ('correct_sequence', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('content', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='game.level')),
            ],
        ),
    ]
