# Generated by Django 5.1.6 on 2025-02-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(default='Drag and drop the blocks into the correct order.'),
        ),
    ]
